version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: internapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Clout#123
      POSTGRES_DB: interns
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: internapp-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:Clout%23123@postgres:5432/interns
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: internapp-frontend
    ports:
      - "5173:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  website:
    build: ./intern-web
    container_name: interns-website
    ports:
      - "5175:5174"
    volumes:
      - ./intern-web:/app
      - /app/node_modules
    command: npm run dev -- --host --port 5174