"""Add expected_output and test_input

Revision ID: 823adeb7e06b
Revises: 
Create Date: 2025-12-12 11:17:03.818390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '823adeb7e06b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_internship_files')
    op.create_foreign_key(None, 'certificates', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'certificates', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'mentor_allocations', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'mentor_allocations', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'mentors', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'students', ['student_id'], ['id'])
    op.add_column('project_tasks', sa.Column('expected_output', sa.String(), nullable=True))
    op.alter_column('project_tasks', 'visible_tests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint(op.f('project_tasks_project_id_fkey'), 'project_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'project_tasks', 'projects', ['project_id'], ['id'])
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_projects_project_type'), table_name='projects')
    op.drop_column('projects', 'project_type')
    op.create_foreign_key(None, 'reports_fortnight', 'students', ['student_id'], ['id'])
    op.alter_column('student_task_status', 'student_project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_task_status', 'last_submission_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('student_task_status', 'mentor_override_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('student_task_status_task_id_fkey'), 'student_task_status', type_='foreignkey')
    op.create_foreign_key(None, 'student_task_status', 'project_tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'student_task_status', 'students', ['student_id'], ['id'])
    op.drop_column('student_task_status', 'is_completed')
    op.drop_column('student_task_status', 'submitted_code')
    op.create_foreign_key(None, 'submissions', 'project_tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'submissions', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.add_column('student_task_status', sa.Column('submitted_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('student_task_status', sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student_task_status', type_='foreignkey')
    op.drop_constraint(None, 'student_task_status', type_='foreignkey')
    op.create_foreign_key(op.f('student_task_status_task_id_fkey'), 'student_task_status', 'project_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('student_task_status', 'mentor_override_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('student_task_status', 'last_submission_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('student_task_status', 'student_project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'reports_fortnight', type_='foreignkey')
    op.add_column('projects', sa.Column('project_type', postgresql.ENUM('fasttrack', 'days45', 'semester4m', name='internship_type'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_projects_project_type'), 'projects', ['project_type'], unique=False)
    op.alter_column('projects', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'project_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('project_tasks_project_id_fkey'), 'project_tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('project_tasks', 'visible_tests',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_column('project_tasks', 'expected_output')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'mentors', type_='foreignkey')
    op.drop_constraint(None, 'mentor_allocations', type_='foreignkey')
    op.drop_constraint(None, 'mentor_allocations', type_='foreignkey')
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.create_table('project_internship_files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('internship_type', postgresql.ENUM('fasttrack', 'days45', 'semester4m', name='internship_type'), autoincrement=False, nullable=False),
    sa.Column('zip_file_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_internship_files_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_internship_files_pkey'))
    )
    # ### end Alembic commands ###
